name: Test, Verify, Publish, and Auto-Merge

on:
  push:
    branches-ignore:
      - main

jobs:
  test-verify-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Determine relevant test classes
        id: extract-tests
        run: |
          chmod +x .github/scripts/test-changes.sh
          .github/scripts/test-changes.sh
        env:
          GITHUB_EVENT_BEFORE: ${{ github.event.before }}
          GITHUB_SHA: ${{ github.sha }}

      - name: Run relevant tests
        if: steps.extract-tests.outputs.run_tests == 'true'
        run: mvn test -Dtest="${{ steps.extract-tests.outputs.test_classes }}"

      - name: Create Pull Request to main
        if: success()
        run: |
          chmod +x .github/scripts/pull-request.sh
          .github/scripts/pull-request.sh
        env:
          GH_TOKEN: ${{ secrets.AUTOMATION_PAT }}
          GITHUB_REF_NAME: ${{ github.ref_name }}

      - name: Run mvn verify
        if: success()
        run: mvn verify

      - name: Run mvn site
        if: success()
        run: mvn site -DskipTests

      - name: Upload site artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: site-artifacts
          path: target/site

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site

      - name: Enable auto-merge
        if: success()
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create_pr.outputs.pull_request_number }}
          merge-method: squash

      - name: Send failure email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Build Failed for Branch ${{ github.ref_name }}'
          to: 'revtrainingemail@gmail.com'
          from: 'AutomationExtravaganzaBot'
          body: |
            Hello,

            The build for branch ${{ github.ref_name }} has failed.
            Please review the logs and make necessary changes.

            Thanks,
            CI Bot
