# .github/workflows/auto-merge-and-publish.yml
name: Auto Merge and Publish

on:
  workflow_run:
    workflows: ["Verify Site on PR"]
    types:
      - completed

jobs:
  merge-and-publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      pages: write
      id-token: write

    steps:
      - name: Download site artifacts
        uses: actions/download-artifact@v4
        with:
          name: site-artifacts
          path: ./target/site

      - name: Check if site artifacts exist
        id: check_artifacts
        run: |
          if [ ! -f ./target/site/index.html ]; then
            echo "Site artifacts not found."
            echo "found=false" >> $GITHUB_OUTPUT
          else
            echo "found=true" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to GitHub Pages
        if: steps.check_artifacts.outputs.found == 'true'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site

      - name: Enable auto-merge
        if: steps.check_artifacts.outputs.found == 'true'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          merge-method: squash

      - name: Fail gracefully if artifacts are missing
        if: steps.check_artifacts.outputs.found == 'false'
        run: |
          echo "Expected site artifacts were not found. Skipping deploy and merge."
          exit 1

  notify-on-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' || failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send failure email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Build or Artifact Failure for PR #${{ github.event.workflow_run.pull_requests[0].number }}'
          to: ${{ github.event.workflow_run.pull_requests[0].user.email }}
          from: 'ci-bot@example.com'
          body: |
            Hello,

            The build for your pull request #${{ github.event.workflow_run.pull_requests[0].number }} either failed or did not produce the expected site artifacts.
            Please review the logs and make necessary changes.

            Thanks,
            CI Bot
