name: Test on Push

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    if: github.event_name == 'push' && !startsWith(github.ref, 'refs/pull/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os}}-maven-
      - name: Determine relevant test classes
        id: changed-tests
        run: |
          .github/scripts/test-changes.sh ${{ github.event.before }} ${{ github.sha }}
        env:
          GITHUB_OUTPUT: ${{ github.step.outputs }}

      - name: Run relevant tests
        if: steps.changed-tests.outputs.run_tests == 'true'
        run: mvn test -Dtest="${{ steps.changed-tests.outputs.test_classes }}"

      - name: Create Pull Request to main
        if: success()
        run: |
          .github/scripts/pull-request.sh
        env:
          GH_TOKEN: ${{ secrets.AUTOMATION_PAT }}
          GITHUB_REF_NAME: ${{ github.ref_name }}

