name: Test on Push

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    if: github.event_name == 'push' && !startsWith(github.ref, 'refs/pull/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os}}-maven-

      - name: Run mvn test
        run: mvn test

      - name: Create Pull Request to main
        if: success()
        run: |
          # Check if a PR already exists from this branch to main
          existing_pr=$(gh pr list --base main --head ${{ github.ref_name }} --json number --jq '.[0].number')

          if [ -z "$existing_pr" ]; then
            echo "No existing PR found. Creating a new one..."
            gh pr create \
              --base main \
              --head ${{ github.ref_name }} \
              --title "Auto PR: ${{ github.ref_name }} to main" \
              --body "This pull request was automatically created after successful tests."
          else
            echo "PR already exists: #$existing_pr"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

